FROM ubuntu:latest

# Install basic utils
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt -y install apt-utils curl python3 python3-dev python3-pip python3-setuptools supervisor
RUN pip3 install boto3
RUN pip3 install pyOpenSSL
RUN pip3 install service_identity
RUN pip3 install Twisted
RUN pip3 install requests
RUN pip3 install awscli

# Install msf and pymetasploit3
RUN curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && chmod 755 msfinstall && ./msfinstall
RUN adduser --disabled-password --gecos "" msf
RUN pip3 install pymetasploit3

# Setup supervisord
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Setup application directories
RUN mkdir /opt/havoc
RUN mkdir /opt/havoc/shared

# Copy repo version of havoc_metasploit.py into build
COPY ./havoc_metasploit.py /opt/havoc/havoc_metasploit.py

# Copy repo version of link.py into build
COPY ./link.py /opt/havoc/link.py
RUN chmod +x /opt/havoc/link.py

# Initialize the metasploit database
USER msf
ENV LANG=en_US.UTF-8 HOME="/home/msf" USER="msf"
RUN /opt/metasploit-framework/bin/msfdb init --user msf --pass 1msf_secured2
USER root
RUN hostnamectl set-hostname metasploit