FROM ubuntu:latest

# Install basic utils
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt -y install apt-utils git curl wget python3 python3-dev python3-pip python3-setuptools python3-venv libaugeas0 supervisor
RUN pip3 install boto3
RUN pip3 install pyOpenSSL
RUN pip3 install service_identity
RUN pip3 install Twisted
RUN pip3 install requests==2.25.0
RUN pip3 install awscli

# Install havoc library
RUN pip3 install havoc

# Install Go
RUN wget -O go1.17.5.linux-amd64.tar.gz https://go.dev/dl/go1.17.5.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.17.5.linux-amd64.tar.gz
RUN export PATH=$PATH:/usr/local/go/bin

# Install Certbot
RUN python3 -m venv /opt/certbot/
RUN /opt/certbot/bin/pip install --upgrade pip
RUN /opt/certbot/bin/pip install certbot
RUN ln -s /opt/certbot/bin/certbot /usr/bin/certbot

# Install HTTPUploadExfil
RUN git clone https://github.com/IngoKl/HTTPUploadExfil.git
WORKDIR /HTTPUploadExfil
RUN /usr/local/go/bin/go build

# Setup supervisord
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Setup application directories
RUN mkdir /opt/havoc
RUN mkdir /opt/havoc/shared

# Copy repo version of havoc_exfilkit.py into build
COPY ./havoc_exfilkit.py /opt/havoc/havoc_exfilkit.py

# Copy repo version of link.py and link.ini into build
COPY ./link.py /opt/havoc/link.py
COPY ./link.ini /opt/havoc/link.ini
RUN chmod +x /opt/havoc/link.py
