FROM ubuntu:latest

# Install basic utils
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt -y install apt-utils git curl python3 python3-dev python3-pip python3-setuptools supervisor ldap-utils smbclient
RUN apt -y install acl attr samba samba-dsdb-modules samba-vfs-modules winbind libpam-winbind libnss-winbind libpam-krb5 krb5-config krb5-user dnsutils chrony
RUN pip3 install boto3
RUN pip3 install pyOpenSSL
RUN pip3 install service_identity
RUN pip3 install Twisted
RUN pip3 install requests
RUN pip3 install awscli

# Install havoc library
RUN pip3 install havoc

# Install additional utils
RUN apt -y install nmap
RUN pip3 install impacket
RUN pip3 install kube-hunter
RUN pip3 install minikerberos
RUN pip3 install ldeep
RUN pip3 install py-altdns==1.0.2
RUN pip3 install aiodnsbrute
RUN pip3 install wmic
RUN pip3 install crackmapexec

# Setup supervisord
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Setup application directories
RUN mkdir /opt/havoc
RUN mkdir /opt/havoc/shared

# Remove smb.conf so that samba-tool can provision a DC
RUN rm /etc/samba/smb.conf

# Copy repo version of havoc_trainman.py into build
COPY ./havoc_trainman.py /opt/havoc/havoc_trainman.py

# Copy repo version of link.py into build
COPY ./link.py /opt/havoc/link.py
RUN chmod +x /opt/havoc/link.py

# Copy AD users list into build and create users directory
COPY ./names.txt /opt/havoc/names.txt
RUN mkdir /opt/havoc/users

# Copy fake data into build
COPY ./sample-data.csv /opt/havoc/sample-data.csv
COPY ./test-5mb.bin /opt/havoc/test-5mb.bin

# CLone Responder repo
RUN git clone https://github.com/lgandx/Responder.git

# Install PyExfil last
RUN git clone https://www.github.com/ytisf/PyExfil
WORKDIR PyExfil
RUN pip3 install -r requirements3.txt
