FROM ubuntu:latest

# Install basic utils
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt -y install apt-utils curl python3 python3-dev python3-pip python3-setuptools supervisor
RUN pip3 install boto3
RUN pip3 install pyOpenSSL
RUN pip3 install service_identity
RUN pip3 install Twisted
RUN pip3 install requests
RUN pip3 install awscli

# Install havoc library
RUN pip3 install havoc

# Install additional utils
RUN apt -y install nmap
RUN pip3 install python-nmap
RUN pip3 install impacket
RUN pip3 install kube-hunter
RUN pip3 install minikerberos
RUN pip3 install ldeep
RUN pip3 install e4l
RUN pip3 install bloodhound
RUN pip3 install py-altdns==1.0.2
RUN pip3 install aiodnsbrute
RUN pip3 install lsassy
RUN pip3 install wmic
RUN pip3 install crackpamexec

# Setup supervisord
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Setup application directories
RUN mkdir /opt/havoc
RUN mkdir /opt/havoc/shared

# Copy repo version of havoc_trainman.py into build
COPY ./havoc_trainman.py /opt/havoc/havoc_trainman.py

# Copy repo version of link.py into build
COPY ./link.py /opt/havoc/link.py
RUN chmod +x /opt/havoc/link.py

# Install PyExfil last
RUN git clone https://www.github.com/ytisf/PyExfil
WORKDIR PyExfil
RUN pip3 install -r requirements.txt
