FROM ubuntu:20.04

# Install basic utils
ENV DEBIAN_FRONTEND=noninteractive
ENV DATABASE_USE=sqlite
RUN apt update
RUN apt -y install apt-utils curl python3 python3-dev python3-pip python3-venv libaugeas0 supervisor git tzdata
RUN pip3 install boto3
RUN pip3 install pyOpenSSL
RUN pip3 install service_identity
RUN pip3 install Twisted
RUN pip3 install requests
RUN pip3 install urllib3
RUN pip3 install awscli

# Install havoc library
RUN pip3 install havoc

# Install Certbot
RUN python3 -m venv /opt/certbot/
RUN /opt/certbot/bin/pip install --upgrade pip
RUN /opt/certbot/bin/pip install certbot
RUN ln -s /opt/certbot/bin/certbot /usr/bin/certbot

# Setup supervisord
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Setup application directories
RUN mkdir /opt/havoc
RUN mkdir /opt/havoc/shared

# Copy repo version of havoc_powershell_empire.py into build
COPY ./havoc_powershell_empire.py /opt/havoc/havoc_powershell_empire.py

# Copy repo version of link.py and link.ini into build
COPY ./link.py /opt/havoc/link.py
COPY ./link.ini /opt/havoc/link.ini
RUN chmod +x /opt/havoc/link.py

# Install custom dependencies and modules
WORKDIR /opt
RUN git clone --recursive -b v4.10.0 https://github.com/BC-SECURITY/Empire.git
WORKDIR Empire
RUN printf "y\ny\nn\n" | ./setup/install.sh
# Rewrite path to empire.db in the Empire build
RUN sed -i "s/data\/empire.db/empire\/server\/data\/empire.db/g" empire/server/server.py