FROM ubuntu:latest

# Install basic utils
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt -y install apt-utils curl python3 python3-dev python3-pip python3-setuptools supervisor git tzdata
RUN pip3 install boto3
RUN pip3 install pyOpenSSL
RUN pip3 install service_identity
RUN pip3 install Twisted
RUN pip3 install requests
RUN pip3 install awscli
RUN pip3 install havoc

# Install custom dependencies and modules
RUN git clone --recursive https://github.com/BC-SECURITY/Empire.git
RUN cd Empire
RUN printf "y\ny\ny\ny\n" | ./setup/install.sh
RUN poetry install
# Fix a bug in the Powershell Empire build
RUN sed -i "s/data\/empire.db/empire\/server\/data\/empire.db/g" empire/server/server.py

# Setup supervisord
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Setup application directories
RUN mkdir /opt/havoc
RUN mkdir /opt/havoc/shared

# Copy repo version of havoc_powershell_empire.py into build
COPY ./havoc_powershell_empire.py /opt/havoc/havoc_powershell_empire.py

# Copy repo version of link.py into build
COPY ./link.py /opt/havoc/link.py
RUN chmod +x /opt/havoc/link.py
