FROM python:3.9.4-buster

# Install basic utils
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt -y install apt-utils curl python3 python3-dev python3-pip supervisor git tzdata
RUN pip3 install boto3
RUN pip3 install pyOpenSSL
RUN pip3 install service_identity
RUN pip3 install Twisted
RUN pip3 install requests
RUN pip3 install awscli

# Install havoc library version 0.2.6
RUN pip3 install havoc

# Setup supervisord
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Setup application directories
RUN mkdir /opt/havoc
RUN mkdir /opt/havoc/shared

# Copy repo version of havoc_powershell_empire.py into build
COPY ./havoc_powershell_empire.py /opt/havoc/havoc_powershell_empire.py

# Copy repo version of link.py into build
COPY ./link.py /opt/havoc/link.py
RUN chmod +x /opt/havoc/link.py

# Install custom dependencies and modules
# Install python3 as python so that poetry can print
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
WORKDIR /opt
RUN git clone --recursive https://github.com/BC-SECURITY/Empire.git
WORKDIR Empire
# Disable poetry virtualenvs.create in the Empire setup/install.sh script
RUN sed -i "s/poetry install/poetry config virtualenvs.create false \&\& poetry install/g" setup/install.sh
RUN printf "y\ny\ny\ny\n" | ./setup/install.sh
# Rewrite path to empire.db in the Empire build
RUN sed -i "s/data\/empire.db/empire\/server\/data\/empire.db/g" empire/server/server.py