FROM ubuntu:latest

# Install basic utils
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt -y install apt-utils curl python3 python3-dev python3-pip python3-setuptools python3-venv libaugeas0 supervisor
RUN pip3 install boto3
RUN pip3 install pyOpenSSL
RUN pip3 install service_identity
RUN pip3 install twisted
RUN pip3 install uploadserver
RUN pip3 install requests==2.29.0
RUN pip3 install awscli

# Install havoc library
RUN pip3 install havoc

# Setup supervisord
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Install Certbot
RUN python3 -m venv /opt/certbot/
RUN /opt/certbot/bin/pip install --upgrade pip
RUN /opt/certbot/bin/pip install certbot
RUN ln -s /opt/certbot/bin/certbot /usr/bin/certbot

# Setup application directories
RUN mkdir /opt/havoc
RUN mkdir /opt/havoc/shared

# Copy repo version of havoc_http_server.py into build
COPY ./havoc_http_server.py /opt/havoc/havoc_http_server.py

# Copy repo version of link.py and link.ini into build
COPY ./link.py /opt/havoc/link.py
COPY ./link.ini /opt/havoc/link.ini
RUN chmod +x /opt/havoc/link.py



